# Generated by Django 5.0.14 on 2026-01-25 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clrSite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text="e.g. '100% Liberian Owned & Managed'", max_length=255)),
                ('icon_class', models.CharField(default='fas fa-check-circle', help_text="FontAwesome class e.g. 'fas fa-check-circle'", max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
