# Generated by Django 5.0.14 on 2026-03-09 06:53

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clrSite', '0002_companyhighlight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='our_mission_vision_statement',
            name='history',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='our_mission_vision_statement',
            name='mission_statement',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='our_mission_vision_statement',
            name='our_purpose',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='our_mission_vision_statement',
            name='our_values',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='our_mission_vision_statement',
            name='vision_statement',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
