# Generated by Django 5.0.14 on 2026-03-09 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clrSite', '0003_alter_our_mission_vision_statement_history_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='image',
            field=models.ImageField(blank=True, upload_to='services/images/'),
        ),
    ]
