# Generated by Django 5.0.14 on 2026-04-03 18:30

import django.utils.timezone
from django.db import migrations, models


def migrate_projects_data(apps, schema_editor):
    Projects = apps.get_model('clrSite', 'Projects')
    ProjectImage = apps.get_model('clrSite', 'ProjectImage')
    
    for project in Projects.objects.all():
        # Set created_at to proj_date if it exists
        if hasattr(project, 'proj_date') and project.proj_date:
            project.created_at = project.proj_date
            project.save(update_fields=['created_at'])
        
        # Create ProjectImage for existing image
        if hasattr(project, 'image') and project.image:
            ProjectImage.objects.create(
                project=project,
                image=project.image,
                caption='',
                order=0
            )


class Migration(migrations.Migration):

    dependencies = [
        ('clrSite', '0005_projectimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.RunPython(migrate_projects_data, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='projects',
            name='image',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='proj_date',
        ),
    ]
