# Generated by Django 5.0.14 on 2025-09-28 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['slug'], name='libraryApp__slug_79220f_idx')],
            },
        ),
        migrations.CreateModel(
            name='BookSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(default="Your Client's Name", max_length=100)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='covers/')),
                ('description', models.TextField()),
                ('access_type', models.CharField(choices=[('free', 'Free'), ('paid', 'Paid'), ('students', 'Students Only')], default='paid', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('preview_pages', models.PositiveIntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(related_name='book_sets', to='libraryApp.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('access_expires', models.DateTimeField(blank=True, null=True)),
                ('book_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='libraryApp.bookset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_student', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume_number', models.PositiveIntegerField()),
                ('title', models.CharField(blank=True, max_length=200)),
                ('pdf_file', models.FileField(upload_to='volumes/')),
                ('preview_pdf', models.FileField(blank=True, upload_to='previews/')),
                ('book_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volumes', to='libraryApp.bookset')),
            ],
            options={
                'ordering': ['volume_number'],
            },
        ),
        migrations.AddIndex(
            model_name='bookset',
            index=models.Index(fields=['title', 'access_type'], name='libraryApp__title_419c51_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['purchased_at'], name='libraryApp__purchas_d8c2fb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='purchase',
            unique_together={('user', 'book_set')},
        ),
        migrations.AlterUniqueTogether(
            name='volume',
            unique_together={('book_set', 'volume_number')},
        ),
    ]
